# Generated by Django 3.2.18 on 2023-04-12 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surver', '0002_access'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surver',
            name='owner',
        ),
    ]
