# Generated by Django 3.2.18 on 2023-04-12 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surver', '0003_remove_surver_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='access',
            old_name='server',
            new_name='surver',
        ),
    ]
