# Generated by Django 3.2.18 on 2023-04-12 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surver', '0004_rename_server_access_surver'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(default='public', max_length=20),
        ),
        migrations.AlterField(
            model_name='channel',
            name='type',
            field=models.CharField(default='text', max_length=20),
        ),
    ]
