# Generated by Django 3.2.18 on 2023-04-12 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surver', '0007_auto_20230412_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surver',
            name='users',
        ),
    ]
