# Generated by Django 3.2.18 on 2023-04-12 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surver', '0008_remove_surver_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access',
            name='type',
            field=models.CharField(default='', max_length=20),
        ),
    ]
