# Generated by Django 3.2.18 on 2023-04-12 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('surver', '0010_surver_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access',
            name='surver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survers', to='surver.surver'),
        ),
        migrations.AlterField(
            model_name='access',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
