# Generated by Django 3.2.18 on 2023-04-13 00:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('surver', '0011_auto_20230413_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surver',
            name='members',
            field=models.ManyToManyField(related_name='survers', through='surver.Access', to=settings.AUTH_USER_MODEL),
        ),
    ]
