# Generated by Django 3.2.18 on 2023-04-13 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surver', '0012_alter_surver_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='reaction',
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(default='good', max_length=20)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='surver.message')),
            ],
        ),
    ]
